/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ApplicationDeploymentRestriction from './ApplicationDeploymentRestriction';
import BaseResponse from './BaseResponse';

/**
 * The ApplicationDeploymentRuleResponse model module.
 * @module model/ApplicationDeploymentRuleResponse
 * @version 1.0.3
 */
class ApplicationDeploymentRuleResponse {
    /**
     * Constructs a new <code>ApplicationDeploymentRuleResponse</code>.
     * @alias module:model/ApplicationDeploymentRuleResponse
     * @implements module:model/BaseResponse
     * @param id {String} 
     * @param createdAt {Date} 
     */
    constructor(id, createdAt) { 
        BaseResponse.initialize(this, id, createdAt);
        ApplicationDeploymentRuleResponse.initialize(this, id, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
    }

    /**
     * Constructs a <code>ApplicationDeploymentRuleResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationDeploymentRuleResponse} obj Optional instance to populate.
     * @return {module:model/ApplicationDeploymentRuleResponse} The populated <code>ApplicationDeploymentRuleResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationDeploymentRuleResponse();
            BaseResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('deployment_restrictions')) {
                obj['deployment_restrictions'] = ApiClient.convertToType(data['deployment_restrictions'], [ApplicationDeploymentRestriction]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ApplicationDeploymentRestriction>} deployment_restrictions
 */
ApplicationDeploymentRuleResponse.prototype['deployment_restrictions'] = undefined;

/**
 * @member {String} id
 */
ApplicationDeploymentRuleResponse.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
ApplicationDeploymentRuleResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ApplicationDeploymentRuleResponse.prototype['updated_at'] = undefined;


// Implement BaseResponse interface:
/**
 * @member {String} id
 */
BaseResponse.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseResponse.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseResponse.prototype['updated_at'] = undefined;




export default ApplicationDeploymentRuleResponse;

