/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApplicationNetworkResponse model module.
 * @module model/ApplicationNetworkResponse
 * @version 1.0.1
 */
class ApplicationNetworkResponse {
    /**
     * Constructs a new <code>ApplicationNetworkResponse</code>.
     * @alias module:model/ApplicationNetworkResponse
     */
    constructor() { 
        
        ApplicationNetworkResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApplicationNetworkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApplicationNetworkResponse} obj Optional instance to populate.
     * @return {module:model/ApplicationNetworkResponse} The populated <code>ApplicationNetworkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApplicationNetworkResponse();

            if (data.hasOwnProperty('sticky_session')) {
                obj['sticky_session'] = ApiClient.convertToType(data['sticky_session'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Specify if the sticky session option (also called persistant session) is activated or not for this application. If activated, user will be redirected by the load balancer to the same instance each time he access to the application.  
 * @member {Boolean} sticky_session
 * @default false
 */
ApplicationNetworkResponse.prototype['sticky_session'] = false;






export default ApplicationNetworkResponse;

