/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ClusterFeatureRequestFeatures from './ClusterFeatureRequestFeatures';

/**
 * The ClusterFeatureRequest model module.
 * @module model/ClusterFeatureRequest
 * @version 1.0.0
 */
class ClusterFeatureRequest {
    /**
     * Constructs a new <code>ClusterFeatureRequest</code>.
     * @alias module:model/ClusterFeatureRequest
     */
    constructor() { 
        
        ClusterFeatureRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClusterFeatureRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterFeatureRequest} obj Optional instance to populate.
     * @return {module:model/ClusterFeatureRequest} The populated <code>ClusterFeatureRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterFeatureRequest();

            if (data.hasOwnProperty('features')) {
                obj['features'] = ApiClient.convertToType(data['features'], [ClusterFeatureRequestFeatures]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ClusterFeatureRequestFeatures>} features
 */
ClusterFeatureRequest.prototype['features'] = undefined;






export default ClusterFeatureRequest;

