/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClusterRegionResponse model module.
 * @module model/ClusterRegionResponse
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ClusterRegionResponse {
    /**
     * Constructs a new <code>ClusterRegionResponse</code>.
     * @alias module:model/ClusterRegionResponse
     * @param name {String} 
     * @param countryCode {String} 
     * @param country {String} 
     * @param city {String} 
     */
    constructor(name, countryCode, country, city) { 
        
        ClusterRegionResponse.initialize(this, name, countryCode, country, city);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, countryCode, country, city) { 
        obj['name'] = name;
        obj['country_code'] = countryCode;
        obj['country'] = country;
        obj['city'] = city;
    }

    /**
     * Constructs a <code>ClusterRegionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterRegionResponse} obj Optional instance to populate.
     * @return {module:model/ClusterRegionResponse} The populated <code>ClusterRegionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterRegionResponse();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ClusterRegionResponse.prototype['name'] = undefined;

/**
 * @member {String} country_code
 */
ClusterRegionResponse.prototype['country_code'] = undefined;

/**
 * @member {String} country
 */
ClusterRegionResponse.prototype['country'] = undefined;

/**
 * @member {String} city
 */
ClusterRegionResponse.prototype['city'] = undefined;






export default ClusterRegionResponse;

