/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ClusterRoutingTableResponseResults model module.
 * @module model/ClusterRoutingTableResponseResults
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ClusterRoutingTableResponseResults {
    /**
     * Constructs a new <code>ClusterRoutingTableResponseResults</code>.
     * @alias module:model/ClusterRoutingTableResponseResults
     */
    constructor() { 
        
        ClusterRoutingTableResponseResults.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClusterRoutingTableResponseResults</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClusterRoutingTableResponseResults} obj Optional instance to populate.
     * @return {module:model/ClusterRoutingTableResponseResults} The populated <code>ClusterRoutingTableResponseResults</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClusterRoutingTableResponseResults();

            if (data.hasOwnProperty('destination')) {
                obj['destination'] = ApiClient.convertToType(data['destination'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} destination
 */
ClusterRoutingTableResponseResults.prototype['destination'] = undefined;

/**
 * @member {String} target
 */
ClusterRoutingTableResponseResults.prototype['target'] = undefined;

/**
 * @member {String} description
 */
ClusterRoutingTableResponseResults.prototype['description'] = undefined;






export default ClusterRoutingTableResponseResults;

