/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ContainerRegistryKind.
* @enum {}
* @readonly
*/
export default class ContainerRegistryKind {
    
        /**
         * value: "ECR"
         * @const
         */
        "ECR" = "ECR";

    
        /**
         * value: "DOCR"
         * @const
         */
        "DOCR" = "DOCR";

    
        /**
         * value: "SCALEWAY_CR"
         * @const
         */
        "SCALEWAY_CR" = "SCALEWAY_CR";

    
        /**
         * value: "DOCKER_HUB"
         * @const
         */
        "DOCKER_HUB" = "DOCKER_HUB";

    
        /**
         * value: "PUBLIC_ECR"
         * @const
         */
        "PUBLIC_ECR" = "PUBLIC_ECR";

    

    /**
    * Returns a <code>ContainerRegistryKind</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ContainerRegistryKind} The enum <code>ContainerRegistryKind</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

