/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerRegistryKindEnum from './ContainerRegistryKindEnum';

/**
 * The ContainerRegistryProviderDetailsResponse model module.
 * @module model/ContainerRegistryProviderDetailsResponse
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ContainerRegistryProviderDetailsResponse {
    /**
     * Constructs a new <code>ContainerRegistryProviderDetailsResponse</code>.
     * @alias module:model/ContainerRegistryProviderDetailsResponse
     * @param id {String} 
     * @param name {String} 
     * @param url {String} URL of the container registry
     * @param kind {module:model/ContainerRegistryKindEnum} 
     */
    constructor(id, name, url, kind) { 
        
        ContainerRegistryProviderDetailsResponse.initialize(this, id, name, url, kind);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, url, kind) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['url'] = url;
        obj['kind'] = kind;
    }

    /**
     * Constructs a <code>ContainerRegistryProviderDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContainerRegistryProviderDetailsResponse} obj Optional instance to populate.
     * @return {module:model/ContainerRegistryProviderDetailsResponse} The populated <code>ContainerRegistryProviderDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerRegistryProviderDetailsResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ContainerRegistryKindEnum.constructFromObject(data['kind']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ContainerRegistryProviderDetailsResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ContainerRegistryProviderDetailsResponse.prototype['name'] = undefined;

/**
 * URL of the container registry
 * @member {String} url
 */
ContainerRegistryProviderDetailsResponse.prototype['url'] = undefined;

/**
 * @member {module:model/ContainerRegistryKindEnum} kind
 */
ContainerRegistryProviderDetailsResponse.prototype['kind'] = undefined;






export default ContainerRegistryProviderDetailsResponse;

