/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomDomainAllOf model module.
 * @module model/CustomDomainAllOf
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class CustomDomainAllOf {
    /**
     * Constructs a new <code>CustomDomainAllOf</code>.
     * @alias module:model/CustomDomainAllOf
     */
    constructor() { 
        
        CustomDomainAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomDomainAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomDomainAllOf} obj Optional instance to populate.
     * @return {module:model/CustomDomainAllOf} The populated <code>CustomDomainAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomDomainAllOf();

            if (data.hasOwnProperty('validation_domain')) {
                obj['validation_domain'] = ApiClient.convertToType(data['validation_domain'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * URL provided by Qovery. You must create a CNAME on your DNS provider using that URL
 * @member {String} validation_domain
 */
CustomDomainAllOf.prototype['validation_domain'] = undefined;

/**
 * @member {module:model/CustomDomainAllOf.StatusEnum} status
 */
CustomDomainAllOf.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CustomDomainAllOf['StatusEnum'] = {

    /**
     * value: "deploying"
     * @const
     */
    "deploying": "deploying",

    /**
     * value: "checking"
     * @const
     */
    "checking": "checking",

    /**
     * value: "ready"
     * @const
     */
    "ready": "ready",

    /**
     * value: "error"
     * @const
     */
    "error": "error"
};



export default CustomDomainAllOf;

