/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ThresholdMetricStatusEnum from './ThresholdMetricStatusEnum';

/**
 * The EnvironmentContainersCurrentScale model module.
 * @module model/EnvironmentContainersCurrentScale
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class EnvironmentContainersCurrentScale {
    /**
     * Constructs a new <code>EnvironmentContainersCurrentScale</code>.
     * @alias module:model/EnvironmentContainersCurrentScale
     */
    constructor() { 
        
        EnvironmentContainersCurrentScale.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EnvironmentContainersCurrentScale</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnvironmentContainersCurrentScale} obj Optional instance to populate.
     * @return {module:model/EnvironmentContainersCurrentScale} The populated <code>EnvironmentContainersCurrentScale</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnvironmentContainersCurrentScale();

            if (data.hasOwnProperty('container')) {
                obj['container'] = ApiClient.convertToType(data['container'], 'String');
            }
            if (data.hasOwnProperty('min')) {
                obj['min'] = ApiClient.convertToType(data['min'], 'Number');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = ApiClient.convertToType(data['max'], 'Number');
            }
            if (data.hasOwnProperty('running')) {
                obj['running'] = ApiClient.convertToType(data['running'], 'Number');
            }
            if (data.hasOwnProperty('running_in_percent')) {
                obj['running_in_percent'] = ApiClient.convertToType(data['running_in_percent'], 'Number');
            }
            if (data.hasOwnProperty('warning_threshold_in_percent')) {
                obj['warning_threshold_in_percent'] = ApiClient.convertToType(data['warning_threshold_in_percent'], 'Number');
            }
            if (data.hasOwnProperty('alert_threshold_in_percent')) {
                obj['alert_threshold_in_percent'] = ApiClient.convertToType(data['alert_threshold_in_percent'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ThresholdMetricStatusEnum.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} container
 */
EnvironmentContainersCurrentScale.prototype['container'] = undefined;

/**
 * @member {Number} min
 */
EnvironmentContainersCurrentScale.prototype['min'] = undefined;

/**
 * @member {Number} max
 */
EnvironmentContainersCurrentScale.prototype['max'] = undefined;

/**
 * @member {Number} running
 */
EnvironmentContainersCurrentScale.prototype['running'] = undefined;

/**
 * @member {Number} running_in_percent
 */
EnvironmentContainersCurrentScale.prototype['running_in_percent'] = undefined;

/**
 * @member {Number} warning_threshold_in_percent
 */
EnvironmentContainersCurrentScale.prototype['warning_threshold_in_percent'] = undefined;

/**
 * @member {Number} alert_threshold_in_percent
 */
EnvironmentContainersCurrentScale.prototype['alert_threshold_in_percent'] = undefined;

/**
 * @member {module:model/ThresholdMetricStatusEnum} status
 */
EnvironmentContainersCurrentScale.prototype['status'] = undefined;

/**
 * @member {Date} updated_at
 */
EnvironmentContainersCurrentScale.prototype['updated_at'] = undefined;






export default EnvironmentContainersCurrentScale;

