/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WeekdayEnum from './WeekdayEnum';

/**
 * The EnvironmentDeploymentRuleEditRequest model module.
 * @module model/EnvironmentDeploymentRuleEditRequest
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class EnvironmentDeploymentRuleEditRequest {
    /**
     * Constructs a new <code>EnvironmentDeploymentRuleEditRequest</code>.
     * @alias module:model/EnvironmentDeploymentRuleEditRequest
     * @param timezone {String} 
     * @param startTime {Date} 
     * @param stopTime {Date} 
     * @param weekdays {Array.<module:model/WeekdayEnum>} 
     */
    constructor(timezone, startTime, stopTime, weekdays) { 
        
        EnvironmentDeploymentRuleEditRequest.initialize(this, timezone, startTime, stopTime, weekdays);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timezone, startTime, stopTime, weekdays) { 
        obj['timezone'] = timezone;
        obj['start_time'] = startTime;
        obj['stop_time'] = stopTime;
        obj['weekdays'] = weekdays;
    }

    /**
     * Constructs a <code>EnvironmentDeploymentRuleEditRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EnvironmentDeploymentRuleEditRequest} obj Optional instance to populate.
     * @return {module:model/EnvironmentDeploymentRuleEditRequest} The populated <code>EnvironmentDeploymentRuleEditRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EnvironmentDeploymentRuleEditRequest();

            if (data.hasOwnProperty('on_demand_preview')) {
                obj['on_demand_preview'] = ApiClient.convertToType(data['on_demand_preview'], 'Boolean');
            }
            if (data.hasOwnProperty('auto_preview')) {
                obj['auto_preview'] = ApiClient.convertToType(data['auto_preview'], 'Boolean');
            }
            if (data.hasOwnProperty('auto_stop')) {
                obj['auto_stop'] = ApiClient.convertToType(data['auto_stop'], 'Boolean');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('stop_time')) {
                obj['stop_time'] = ApiClient.convertToType(data['stop_time'], 'Date');
            }
            if (data.hasOwnProperty('weekdays')) {
                obj['weekdays'] = ApiClient.convertToType(data['weekdays'], [WeekdayEnum]);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} on_demand_preview
 * @default false
 */
EnvironmentDeploymentRuleEditRequest.prototype['on_demand_preview'] = false;

/**
 * @member {Boolean} auto_preview
 * @default false
 */
EnvironmentDeploymentRuleEditRequest.prototype['auto_preview'] = false;

/**
 * @member {Boolean} auto_stop
 * @default false
 */
EnvironmentDeploymentRuleEditRequest.prototype['auto_stop'] = false;

/**
 * @member {String} timezone
 */
EnvironmentDeploymentRuleEditRequest.prototype['timezone'] = undefined;

/**
 * @member {Date} start_time
 */
EnvironmentDeploymentRuleEditRequest.prototype['start_time'] = undefined;

/**
 * @member {Date} stop_time
 */
EnvironmentDeploymentRuleEditRequest.prototype['stop_time'] = undefined;

/**
 * @member {Array.<module:model/WeekdayEnum>} weekdays
 */
EnvironmentDeploymentRuleEditRequest.prototype['weekdays'] = undefined;






export default EnvironmentDeploymentRuleEditRequest;

