/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GcpCredentialsRequest model module.
 * @module model/GcpCredentialsRequest
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class GcpCredentialsRequest {
    /**
     * Constructs a new <code>GcpCredentialsRequest</code>.
     * @alias module:model/GcpCredentialsRequest
     * @param name {String} 
     * @param gcpCredentials {String} 
     */
    constructor(name, gcpCredentials) { 
        
        GcpCredentialsRequest.initialize(this, name, gcpCredentials);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, gcpCredentials) { 
        obj['name'] = name;
        obj['gcp_credentials'] = gcpCredentials;
    }

    /**
     * Constructs a <code>GcpCredentialsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GcpCredentialsRequest} obj Optional instance to populate.
     * @return {module:model/GcpCredentialsRequest} The populated <code>GcpCredentialsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GcpCredentialsRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('gcp_credentials')) {
                obj['gcp_credentials'] = ApiClient.convertToType(data['gcp_credentials'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GcpCredentialsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GcpCredentialsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GcpCredentialsRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['gcp_credentials'] && !(typeof data['gcp_credentials'] === 'string' || data['gcp_credentials'] instanceof String)) {
            throw new Error("Expected the field `gcp_credentials` to be a primitive type in the JSON string but got " + data['gcp_credentials']);
        }

        return true;
    }


}

GcpCredentialsRequest.RequiredProperties = ["name", "gcp_credentials"];

/**
 * @member {String} name
 */
GcpCredentialsRequest.prototype['name'] = undefined;

/**
 * @member {String} gcp_credentials
 */
GcpCredentialsRequest.prototype['gcp_credentials'] = undefined;






export default GcpCredentialsRequest;

