/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelmResponseAllOfSourceOneOf1RepositoryRepository model module.
 * @module model/HelmResponseAllOfSourceOneOf1RepositoryRepository
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class HelmResponseAllOfSourceOneOf1RepositoryRepository {
    /**
     * Constructs a new <code>HelmResponseAllOfSourceOneOf1RepositoryRepository</code>.
     * @alias module:model/HelmResponseAllOfSourceOneOf1RepositoryRepository
     * @param id {String} The id of the helm repository
     * @param name {String} The name of the helm repository
     * @param url {String} The url the helm repository
     */
    constructor(id, name, url) { 
        
        HelmResponseAllOfSourceOneOf1RepositoryRepository.initialize(this, id, name, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, url) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['url'] = url;
    }

    /**
     * Constructs a <code>HelmResponseAllOfSourceOneOf1RepositoryRepository</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelmResponseAllOfSourceOneOf1RepositoryRepository} obj Optional instance to populate.
     * @return {module:model/HelmResponseAllOfSourceOneOf1RepositoryRepository} The populated <code>HelmResponseAllOfSourceOneOf1RepositoryRepository</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelmResponseAllOfSourceOneOf1RepositoryRepository();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelmResponseAllOfSourceOneOf1RepositoryRepository</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelmResponseAllOfSourceOneOf1RepositoryRepository</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HelmResponseAllOfSourceOneOf1RepositoryRepository.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}

HelmResponseAllOfSourceOneOf1RepositoryRepository.RequiredProperties = ["id", "name", "url"];

/**
 * The id of the helm repository
 * @member {String} id
 */
HelmResponseAllOfSourceOneOf1RepositoryRepository.prototype['id'] = undefined;

/**
 * The name of the helm repository
 * @member {String} name
 */
HelmResponseAllOfSourceOneOf1RepositoryRepository.prototype['name'] = undefined;

/**
 * The url the helm repository
 * @member {String} url
 */
HelmResponseAllOfSourceOneOf1RepositoryRepository.prototype['url'] = undefined;






export default HelmResponseAllOfSourceOneOf1RepositoryRepository;

