/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HelmRequestAllOfSourceGit from './HelmRequestAllOfSourceGit';
import HelmResponseAllOfSourceRepository from './HelmResponseAllOfSourceRepository';

/**
 * The HelmResponseAllOfSource model module.
 * @module model/HelmResponseAllOfSource
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class HelmResponseAllOfSource {
    /**
     * Constructs a new <code>HelmResponseAllOfSource</code>.
     * @alias module:model/HelmResponseAllOfSource
     */
    constructor() { 
        
        HelmResponseAllOfSource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HelmResponseAllOfSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelmResponseAllOfSource} obj Optional instance to populate.
     * @return {module:model/HelmResponseAllOfSource} The populated <code>HelmResponseAllOfSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelmResponseAllOfSource();

            if (data.hasOwnProperty('git')) {
                obj['git'] = HelmRequestAllOfSourceGit.constructFromObject(data['git']);
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = HelmResponseAllOfSourceRepository.constructFromObject(data['repository']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/HelmRequestAllOfSourceGit} git
 */
HelmResponseAllOfSource.prototype['git'] = undefined;

/**
 * @member {module:model/HelmResponseAllOfSourceRepository} repository
 */
HelmResponseAllOfSource.prototype['repository'] = undefined;






export default HelmResponseAllOfSource;

