/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import InviteMemberResponseAllOf from './InviteMemberResponseAllOf';
import InviteMemberRoleEnum from './InviteMemberRoleEnum';
import InviteStatusEnum from './InviteStatusEnum';

/**
 * The InviteMemberResponse model module.
 * @module model/InviteMemberResponse
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class InviteMemberResponse {
    /**
     * Constructs a new <code>InviteMemberResponse</code>.
     * @alias module:model/InviteMemberResponse
     * @implements module:model/BaseResponse
     * @implements module:model/InviteMemberResponseAllOf
     * @param id {String} 
     * @param createdAt {Date} 
     * @param email {String} 
     * @param role {module:model/InviteMemberRoleEnum} 
     * @param invitationLink {String} 
     * @param invitationStatus {module:model/InviteStatusEnum} 
     * @param inviter {String} 
     */
    constructor(id, createdAt, email, role, invitationLink, invitationStatus, inviter) { 
        BaseResponse.initialize(this, id, createdAt);InviteMemberResponseAllOf.initialize(this, email, role, invitationLink, invitationStatus, inviter);
        InviteMemberResponse.initialize(this, id, createdAt, email, role, invitationLink, invitationStatus, inviter);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, email, role, invitationLink, invitationStatus, inviter) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['email'] = email;
        obj['role'] = role;
        obj['invitation_link'] = invitationLink;
        obj['invitation_status'] = invitationStatus;
        obj['inviter'] = inviter;
    }

    /**
     * Constructs a <code>InviteMemberResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InviteMemberResponse} obj Optional instance to populate.
     * @return {module:model/InviteMemberResponse} The populated <code>InviteMemberResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteMemberResponse();
            BaseResponse.constructFromObject(data, obj);
            InviteMemberResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = InviteMemberRoleEnum.constructFromObject(data['role']);
            }
            if (data.hasOwnProperty('invitation_link')) {
                obj['invitation_link'] = ApiClient.convertToType(data['invitation_link'], 'String');
            }
            if (data.hasOwnProperty('invitation_status')) {
                obj['invitation_status'] = InviteStatusEnum.constructFromObject(data['invitation_status']);
            }
            if (data.hasOwnProperty('inviter')) {
                obj['inviter'] = ApiClient.convertToType(data['inviter'], 'String');
            }
            if (data.hasOwnProperty('logo_url')) {
                obj['logo_url'] = ApiClient.convertToType(data['logo_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
InviteMemberResponse.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
InviteMemberResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
InviteMemberResponse.prototype['updated_at'] = undefined;

/**
 * @member {String} email
 */
InviteMemberResponse.prototype['email'] = undefined;

/**
 * @member {module:model/InviteMemberRoleEnum} role
 */
InviteMemberResponse.prototype['role'] = undefined;

/**
 * @member {String} invitation_link
 */
InviteMemberResponse.prototype['invitation_link'] = undefined;

/**
 * @member {module:model/InviteStatusEnum} invitation_status
 */
InviteMemberResponse.prototype['invitation_status'] = undefined;

/**
 * @member {String} inviter
 */
InviteMemberResponse.prototype['inviter'] = undefined;

/**
 * @member {String} logo_url
 */
InviteMemberResponse.prototype['logo_url'] = undefined;


// Implement BaseResponse interface:
/**
 * @member {String} id
 */
BaseResponse.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseResponse.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseResponse.prototype['updated_at'] = undefined;
// Implement InviteMemberResponseAllOf interface:
/**
 * @member {String} email
 */
InviteMemberResponseAllOf.prototype['email'] = undefined;
/**
 * @member {module:model/InviteMemberRoleEnum} role
 */
InviteMemberResponseAllOf.prototype['role'] = undefined;
/**
 * @member {String} invitation_link
 */
InviteMemberResponseAllOf.prototype['invitation_link'] = undefined;
/**
 * @member {module:model/InviteStatusEnum} invitation_status
 */
InviteMemberResponseAllOf.prototype['invitation_status'] = undefined;
/**
 * @member {String} inviter
 */
InviteMemberResponseAllOf.prototype['inviter'] = undefined;
/**
 * @member {String} logo_url
 */
InviteMemberResponseAllOf.prototype['logo_url'] = undefined;




export default InviteMemberResponse;

