/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Base from './Base';
import DeploymentRestrictionModeEnum from './DeploymentRestrictionModeEnum';
import DeploymentRestrictionTypeEnum from './DeploymentRestrictionTypeEnum';
import JobDeploymentRestrictionRequest from './JobDeploymentRestrictionRequest';

/**
 * The JobDeploymentRestrictionResponse model module.
 * @module model/JobDeploymentRestrictionResponse
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class JobDeploymentRestrictionResponse {
    /**
     * Constructs a new <code>JobDeploymentRestrictionResponse</code>.
     * @alias module:model/JobDeploymentRestrictionResponse
     * @implements module:model/Base
     * @implements module:model/JobDeploymentRestrictionRequest
     * @param id {String} 
     * @param createdAt {Date} 
     * @param mode {module:model/DeploymentRestrictionModeEnum} 
     * @param type {module:model/DeploymentRestrictionTypeEnum} 
     * @param value {String} For `PATH` restrictions, the value must not start with `/`
     */
    constructor(id, createdAt, mode, type, value) { 
        Base.initialize(this, id, createdAt);JobDeploymentRestrictionRequest.initialize(this, mode, type, value);
        JobDeploymentRestrictionResponse.initialize(this, id, createdAt, mode, type, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, mode, type, value) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['mode'] = mode;
        obj['type'] = type;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>JobDeploymentRestrictionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobDeploymentRestrictionResponse} obj Optional instance to populate.
     * @return {module:model/JobDeploymentRestrictionResponse} The populated <code>JobDeploymentRestrictionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobDeploymentRestrictionResponse();
            Base.constructFromObject(data, obj);
            JobDeploymentRestrictionRequest.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = DeploymentRestrictionModeEnum.constructFromObject(data['mode']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = DeploymentRestrictionTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
JobDeploymentRestrictionResponse.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
JobDeploymentRestrictionResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
JobDeploymentRestrictionResponse.prototype['updated_at'] = undefined;

/**
 * @member {module:model/DeploymentRestrictionModeEnum} mode
 */
JobDeploymentRestrictionResponse.prototype['mode'] = undefined;

/**
 * @member {module:model/DeploymentRestrictionTypeEnum} type
 */
JobDeploymentRestrictionResponse.prototype['type'] = undefined;

/**
 * For `PATH` restrictions, the value must not start with `/`
 * @member {String} value
 */
JobDeploymentRestrictionResponse.prototype['value'] = undefined;


// Implement Base interface:
/**
 * @member {String} id
 */
Base.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
Base.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
Base.prototype['updated_at'] = undefined;
// Implement JobDeploymentRestrictionRequest interface:
/**
 * @member {module:model/DeploymentRestrictionModeEnum} mode
 */
JobDeploymentRestrictionRequest.prototype['mode'] = undefined;
/**
 * @member {module:model/DeploymentRestrictionTypeEnum} type
 */
JobDeploymentRestrictionRequest.prototype['type'] = undefined;
/**
 * For `PATH` restrictions, the value must not start with `/`
 * @member {String} value
 */
JobDeploymentRestrictionRequest.prototype['value'] = undefined;




export default JobDeploymentRestrictionResponse;

