/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListEnvironmentLogs200ResponseInnerMessage model module.
 * @module model/ListEnvironmentLogs200ResponseInnerMessage
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ListEnvironmentLogs200ResponseInnerMessage {
    /**
     * Constructs a new <code>ListEnvironmentLogs200ResponseInnerMessage</code>.
     * @alias module:model/ListEnvironmentLogs200ResponseInnerMessage
     */
    constructor() { 
        
        ListEnvironmentLogs200ResponseInnerMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListEnvironmentLogs200ResponseInnerMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListEnvironmentLogs200ResponseInnerMessage} obj Optional instance to populate.
     * @return {module:model/ListEnvironmentLogs200ResponseInnerMessage} The populated <code>ListEnvironmentLogs200ResponseInnerMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListEnvironmentLogs200ResponseInnerMessage();

            if (data.hasOwnProperty('safe_message')) {
                obj['safe_message'] = ApiClient.convertToType(data['safe_message'], 'String');
            }
            if (data.hasOwnProperty('full_details')) {
                obj['full_details'] = ApiClient.convertToType(data['full_details'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} safe_message
 */
ListEnvironmentLogs200ResponseInnerMessage.prototype['safe_message'] = undefined;

/**
 * @member {String} full_details
 */
ListEnvironmentLogs200ResponseInnerMessage.prototype['full_details'] = undefined;






export default ListEnvironmentLogs200ResponseInnerMessage;

