/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListEnvironmentLogs200ResponseInnerDetails from './ListEnvironmentLogs200ResponseInnerDetails';
import ListEnvironmentLogs200ResponseInnerError from './ListEnvironmentLogs200ResponseInnerError';
import ListEnvironmentLogs200ResponseInnerMessage from './ListEnvironmentLogs200ResponseInnerMessage';

/**
 * The ListEnvironmentLogs200ResponseInner model module.
 * @module model/ListEnvironmentLogs200ResponseInner
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ListEnvironmentLogs200ResponseInner {
    /**
     * Constructs a new <code>ListEnvironmentLogs200ResponseInner</code>.
     * @alias module:model/ListEnvironmentLogs200ResponseInner
     * @param id {String} 
     * @param timestamp {Date} 
     * @param details {module:model/ListEnvironmentLogs200ResponseInnerDetails} 
     */
    constructor(id, timestamp, details) { 
        
        ListEnvironmentLogs200ResponseInner.initialize(this, id, timestamp, details);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, timestamp, details) { 
        obj['id'] = id;
        obj['timestamp'] = timestamp;
        obj['details'] = details;
    }

    /**
     * Constructs a <code>ListEnvironmentLogs200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListEnvironmentLogs200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ListEnvironmentLogs200ResponseInner} The populated <code>ListEnvironmentLogs200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListEnvironmentLogs200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ListEnvironmentLogs200ResponseInnerDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ListEnvironmentLogs200ResponseInnerError.constructFromObject(data['error']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ListEnvironmentLogs200ResponseInnerMessage.constructFromObject(data['message']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ListEnvironmentLogs200ResponseInner.prototype['id'] = undefined;

/**
 * @member {Date} timestamp
 */
ListEnvironmentLogs200ResponseInner.prototype['timestamp'] = undefined;

/**
 * @member {module:model/ListEnvironmentLogs200ResponseInnerDetails} details
 */
ListEnvironmentLogs200ResponseInner.prototype['details'] = undefined;

/**
 * @member {module:model/ListEnvironmentLogs200ResponseInnerError} error
 */
ListEnvironmentLogs200ResponseInner.prototype['error'] = undefined;

/**
 * @member {module:model/ListEnvironmentLogs200ResponseInnerMessage} message
 */
ListEnvironmentLogs200ResponseInner.prototype['message'] = undefined;






export default ListEnvironmentLogs200ResponseInner;

