/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetricGenericDatapoint from './MetricGenericDatapoint';

/**
 * The MetricGeneric model module.
 * @module model/MetricGeneric
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class MetricGeneric {
    /**
     * Constructs a new <code>MetricGeneric</code>.
     * @alias module:model/MetricGeneric
     * @param instanceName {String} 
     * @param data {Array.<module:model/MetricGenericDatapoint>} 
     */
    constructor(instanceName, data) { 
        
        MetricGeneric.initialize(this, instanceName, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instanceName, data) { 
        obj['instance_name'] = instanceName;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>MetricGeneric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetricGeneric} obj Optional instance to populate.
     * @return {module:model/MetricGeneric} The populated <code>MetricGeneric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetricGeneric();

            if (data.hasOwnProperty('instance_name')) {
                obj['instance_name'] = ApiClient.convertToType(data['instance_name'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [MetricGenericDatapoint]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} instance_name
 */
MetricGeneric.prototype['instance_name'] = undefined;

/**
 * @member {Array.<module:model/MetricGenericDatapoint>} data
 */
MetricGeneric.prototype['data'] = undefined;






export default MetricGeneric;

