/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetricMemoryDatapoint from './MetricMemoryDatapoint';

/**
 * The MetricMemory model module.
 * @module model/MetricMemory
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class MetricMemory {
    /**
     * Constructs a new <code>MetricMemory</code>.
     * @alias module:model/MetricMemory
     * @param instanceName {String} 
     * @param data {Array.<module:model/MetricMemoryDatapoint>} 
     */
    constructor(instanceName, data) { 
        
        MetricMemory.initialize(this, instanceName, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instanceName, data) { 
        obj['instance_name'] = instanceName;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>MetricMemory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetricMemory} obj Optional instance to populate.
     * @return {module:model/MetricMemory} The populated <code>MetricMemory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetricMemory();

            if (data.hasOwnProperty('instance_name')) {
                obj['instance_name'] = ApiClient.convertToType(data['instance_name'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [MetricMemoryDatapoint]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} instance_name
 */
MetricMemory.prototype['instance_name'] = undefined;

/**
 * @member {Array.<module:model/MetricMemoryDatapoint>} data
 */
MetricMemory.prototype['data'] = undefined;






export default MetricMemory;

