/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrganizationApiTokenScope from './OrganizationApiTokenScope';

/**
 * The OrganizationApiTokenCreateResponseAllOf model module.
 * @module model/OrganizationApiTokenCreateResponseAllOf
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class OrganizationApiTokenCreateResponseAllOf {
    /**
     * Constructs a new <code>OrganizationApiTokenCreateResponseAllOf</code>.
     * @alias module:model/OrganizationApiTokenCreateResponseAllOf
     */
    constructor() { 
        
        OrganizationApiTokenCreateResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationApiTokenCreateResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationApiTokenCreateResponseAllOf} obj Optional instance to populate.
     * @return {module:model/OrganizationApiTokenCreateResponseAllOf} The populated <code>OrganizationApiTokenCreateResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationApiTokenCreateResponseAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = OrganizationApiTokenScope.constructFromObject(data['scope']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
OrganizationApiTokenCreateResponseAllOf.prototype['name'] = undefined;

/**
 * @member {String} description
 */
OrganizationApiTokenCreateResponseAllOf.prototype['description'] = undefined;

/**
 * the generated token to send in 'Authorization' header prefixed by 'Token '
 * @member {String} token
 */
OrganizationApiTokenCreateResponseAllOf.prototype['token'] = undefined;

/**
 * @member {module:model/OrganizationApiTokenScope} scope
 */
OrganizationApiTokenCreateResponseAllOf.prototype['scope'] = undefined;






export default OrganizationApiTokenCreateResponseAllOf;

