/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import ProjectResponseAllOf from './ProjectResponseAllOf';
import ReferenceObject from './ReferenceObject';

/**
 * The ProjectResponse model module.
 * @module model/ProjectResponse
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ProjectResponse {
    /**
     * Constructs a new <code>ProjectResponse</code>.
     * @alias module:model/ProjectResponse
     * @implements module:model/BaseResponse
     * @implements module:model/ProjectResponseAllOf
     * @param id {String} 
     * @param createdAt {Date} 
     * @param name {String} 
     */
    constructor(id, createdAt, name) { 
        BaseResponse.initialize(this, id, createdAt);ProjectResponseAllOf.initialize(this, name);
        ProjectResponse.initialize(this, id, createdAt, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, name) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ProjectResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectResponse} obj Optional instance to populate.
     * @return {module:model/ProjectResponse} The populated <code>ProjectResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectResponse();
            BaseResponse.constructFromObject(data, obj);
            ProjectResponseAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ReferenceObject.constructFromObject(data['organization']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProjectResponse.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
ProjectResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ProjectResponse.prototype['updated_at'] = undefined;

/**
 * @member {String} name
 */
ProjectResponse.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ProjectResponse.prototype['description'] = undefined;

/**
 * @member {module:model/ReferenceObject} organization
 */
ProjectResponse.prototype['organization'] = undefined;


// Implement BaseResponse interface:
/**
 * @member {String} id
 */
BaseResponse.prototype['id'] = undefined;
/**
 * @member {Date} created_at
 */
BaseResponse.prototype['created_at'] = undefined;
/**
 * @member {Date} updated_at
 */
BaseResponse.prototype['updated_at'] = undefined;
// Implement ProjectResponseAllOf interface:
/**
 * @member {String} name
 */
ProjectResponseAllOf.prototype['name'] = undefined;
/**
 * @member {String} description
 */
ProjectResponseAllOf.prototype['description'] = undefined;
/**
 * @member {module:model/ReferenceObject} organization
 */
ProjectResponseAllOf.prototype['organization'] = undefined;




export default ProjectResponse;

