/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReferenceObject from './ReferenceObject';

/**
 * The ProjectResponseAllOf model module.
 * @module model/ProjectResponseAllOf
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ProjectResponseAllOf {
    /**
     * Constructs a new <code>ProjectResponseAllOf</code>.
     * @alias module:model/ProjectResponseAllOf
     * @param name {String} 
     */
    constructor(name) { 
        
        ProjectResponseAllOf.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ProjectResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectResponseAllOf} obj Optional instance to populate.
     * @return {module:model/ProjectResponseAllOf} The populated <code>ProjectResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectResponseAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ReferenceObject.constructFromObject(data['organization']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ProjectResponseAllOf.prototype['name'] = undefined;

/**
 * @member {String} description
 */
ProjectResponseAllOf.prototype['description'] = undefined;

/**
 * @member {module:model/ReferenceObject} organization
 */
ProjectResponseAllOf.prototype['organization'] = undefined;






export default ProjectResponseAllOf;

