/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScalewayCredentialsRequest model module.
 * @module model/ScalewayCredentialsRequest
 * @version 1.0.1
 */
class ScalewayCredentialsRequest {
    /**
     * Constructs a new <code>ScalewayCredentialsRequest</code>.
     * @alias module:model/ScalewayCredentialsRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        ScalewayCredentialsRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ScalewayCredentialsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScalewayCredentialsRequest} obj Optional instance to populate.
     * @return {module:model/ScalewayCredentialsRequest} The populated <code>ScalewayCredentialsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScalewayCredentialsRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('scaleway_access_key')) {
                obj['scaleway_access_key'] = ApiClient.convertToType(data['scaleway_access_key'], 'String');
            }
            if (data.hasOwnProperty('scaleway_secret_key')) {
                obj['scaleway_secret_key'] = ApiClient.convertToType(data['scaleway_secret_key'], 'String');
            }
            if (data.hasOwnProperty('scaleway_project_id')) {
                obj['scaleway_project_id'] = ApiClient.convertToType(data['scaleway_project_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
ScalewayCredentialsRequest.prototype['name'] = undefined;

/**
 * @member {String} scaleway_access_key
 */
ScalewayCredentialsRequest.prototype['scaleway_access_key'] = undefined;

/**
 * @member {String} scaleway_secret_key
 */
ScalewayCredentialsRequest.prototype['scaleway_secret_key'] = undefined;

/**
 * @member {String} scaleway_project_id
 */
ScalewayCredentialsRequest.prototype['scaleway_project_id'] = undefined;






export default ScalewayCredentialsRequest;

