/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StorageTypeEnum from './StorageTypeEnum';

/**
 * The ServiceStorageStorageInner model module.
 * @module model/ServiceStorageStorageInner
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class ServiceStorageStorageInner {
    /**
     * Constructs a new <code>ServiceStorageStorageInner</code>.
     * @alias module:model/ServiceStorageStorageInner
     * @param id {String} 
     * @param type {module:model/StorageTypeEnum} 
     * @param size {Number} unit is GB
     * @param mountPoint {String} 
     */
    constructor(id, type, size, mountPoint) { 
        
        ServiceStorageStorageInner.initialize(this, id, type, size, mountPoint);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, type, size, mountPoint) { 
        obj['id'] = id;
        obj['type'] = type;
        obj['size'] = size;
        obj['mount_point'] = mountPoint;
    }

    /**
     * Constructs a <code>ServiceStorageStorageInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceStorageStorageInner} obj Optional instance to populate.
     * @return {module:model/ServiceStorageStorageInner} The populated <code>ServiceStorageStorageInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceStorageStorageInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = StorageTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('mount_point')) {
                obj['mount_point'] = ApiClient.convertToType(data['mount_point'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ServiceStorageStorageInner.prototype['id'] = undefined;

/**
 * @member {module:model/StorageTypeEnum} type
 */
ServiceStorageStorageInner.prototype['type'] = undefined;

/**
 * unit is GB
 * @member {Number} size
 */
ServiceStorageStorageInner.prototype['size'] = undefined;

/**
 * @member {String} mount_point
 */
ServiceStorageStorageInner.prototype['mount_point'] = undefined;






export default ServiceStorageStorageInner;

