/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIVariableScopeEnum from './APIVariableScopeEnum';

/**
 * The VariableOverrideRequest model module.
 * @module model/VariableOverrideRequest
 * @version $(grep &#39;version&#39; _build/openapi.yaml | head -1 | tr &#39;:&#39; &#39;\n&#39; | tail -1 | tr -d &#39; &#39;)
 */
class VariableOverrideRequest {
    /**
     * Constructs a new <code>VariableOverrideRequest</code>.
     * @alias module:model/VariableOverrideRequest
     * @param value {String} the value to be used as Override of the targeted environment variable.
     * @param overrideScope {module:model/APIVariableScopeEnum} 
     * @param overrideParentId {String} the id of the variable that is aliased.
     */
    constructor(value, overrideScope, overrideParentId) { 
        
        VariableOverrideRequest.initialize(this, value, overrideScope, overrideParentId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, overrideScope, overrideParentId) { 
        obj['value'] = value;
        obj['override_scope'] = overrideScope;
        obj['override_parent_id'] = overrideParentId;
    }

    /**
     * Constructs a <code>VariableOverrideRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VariableOverrideRequest} obj Optional instance to populate.
     * @return {module:model/VariableOverrideRequest} The populated <code>VariableOverrideRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VariableOverrideRequest();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('override_scope')) {
                obj['override_scope'] = APIVariableScopeEnum.constructFromObject(data['override_scope']);
            }
            if (data.hasOwnProperty('override_parent_id')) {
                obj['override_parent_id'] = ApiClient.convertToType(data['override_parent_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VariableOverrideRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VariableOverrideRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VariableOverrideRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }
        // ensure the json data is a string
        if (data['override_parent_id'] && !(typeof data['override_parent_id'] === 'string' || data['override_parent_id'] instanceof String)) {
            throw new Error("Expected the field `override_parent_id` to be a primitive type in the JSON string but got " + data['override_parent_id']);
        }

        return true;
    }


}

VariableOverrideRequest.RequiredProperties = ["value", "override_scope", "override_parent_id"];

/**
 * the value to be used as Override of the targeted environment variable.
 * @member {String} value
 */
VariableOverrideRequest.prototype['value'] = undefined;

/**
 * @member {module:model/APIVariableScopeEnum} override_scope
 */
VariableOverrideRequest.prototype['override_scope'] = undefined;

/**
 * the id of the variable that is aliased.
 * @member {String} override_parent_id
 */
VariableOverrideRequest.prototype['override_parent_id'] = undefined;






export default VariableOverrideRequest;

