/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoveryApi);
  }
}(this, function(expect, QoveryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoveryApi.PaidUsageResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaidUsageResponse', function() {
    it('should create an instance of PaidUsageResponse', function() {
      // uncomment below and update the code to test PaidUsageResponse
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be.a(QoveryApi.PaidUsageResponse);
    });

    it('should have the property maxDeploymentsPerMonth (base name: "max_deployments_per_month")', function() {
      // uncomment below and update the code to test the property maxDeploymentsPerMonth
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property consumedDeployments (base name: "consumed_deployments")', function() {
      // uncomment below and update the code to test the property consumedDeployments
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property monthlyPlanCost (base name: "monthly_plan_cost")', function() {
      // uncomment below and update the code to test the property monthlyPlanCost
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property monthlyPlanCostInCents (base name: "monthly_plan_cost_in_cents")', function() {
      // uncomment below and update the code to test the property monthlyPlanCostInCents
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property remainingDeployments (base name: "remaining_deployments")', function() {
      // uncomment below and update the code to test the property remainingDeployments
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property deploymentsExceeded (base name: "deployments_exceeded")', function() {
      // uncomment below and update the code to test the property deploymentsExceeded
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

    it('should have the property renewalAt (base name: "renewal_at")', function() {
      // uncomment below and update the code to test the property renewalAt
      //var instance = new QoveryApi.PaidUsageResponse();
      //expect(instance).to.be();
    });

  });

}));
