/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BetaQoveryApi);
  }
}(this, function(expect, BetaQoveryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BetaQoveryApi.ProjectStatsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectStatsResponse', function() {
    it('should create an instance of ProjectStatsResponse', function() {
      // uncomment below and update the code to test ProjectStatsResponse
      //var instance = new BetaQoveryApi.ProjectStatsResponse();
      //expect(instance).to.be.a(BetaQoveryApi.ProjectStatsResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BetaQoveryApi.ProjectStatsResponse();
      //expect(instance).to.be();
    });

    it('should have the property serviceTotalNumber (base name: "service_total_number")', function() {
      // uncomment below and update the code to test the property serviceTotalNumber
      //var instance = new BetaQoveryApi.ProjectStatsResponse();
      //expect(instance).to.be();
    });

    it('should have the property environmentTotalNumber (base name: "environment_total_number")', function() {
      // uncomment below and update the code to test the property environmentTotalNumber
      //var instance = new BetaQoveryApi.ProjectStatsResponse();
      //expect(instance).to.be();
    });

  });

}));
