/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoveryApi);
  }
}(this, function(expect, QoveryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoveryApi.CloudProviderApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CloudProviderApi', function() {
    describe('listAWSEKSInstanceType', function() {
      it('should call listAWSEKSInstanceType successfully', function(done) {
        //uncomment below and update the code to test listAWSEKSInstanceType
        //instance.listAWSEKSInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSEc2InstanceType', function() {
      it('should call listAWSEc2InstanceType successfully', function(done) {
        //uncomment below and update the code to test listAWSEc2InstanceType
        //instance.listAWSEc2InstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSFeatures', function() {
      it('should call listAWSFeatures successfully', function(done) {
        //uncomment below and update the code to test listAWSFeatures
        //instance.listAWSFeatures(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSInstanceType', function() {
      it('should call listAWSInstanceType successfully', function(done) {
        //uncomment below and update the code to test listAWSInstanceType
        //instance.listAWSInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSManagedDatabaseInstanceType', function() {
      it('should call listAWSManagedDatabaseInstanceType successfully', function(done) {
        //uncomment below and update the code to test listAWSManagedDatabaseInstanceType
        //instance.listAWSManagedDatabaseInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSManagedDatabaseType', function() {
      it('should call listAWSManagedDatabaseType successfully', function(done) {
        //uncomment below and update the code to test listAWSManagedDatabaseType
        //instance.listAWSManagedDatabaseType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAWSRegions', function() {
      it('should call listAWSRegions successfully', function(done) {
        //uncomment below and update the code to test listAWSRegions
        //instance.listAWSRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCloudProvider', function() {
      it('should call listCloudProvider successfully', function(done) {
        //uncomment below and update the code to test listCloudProvider
        //instance.listCloudProvider(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDOFeatures', function() {
      it('should call listDOFeatures successfully', function(done) {
        //uncomment below and update the code to test listDOFeatures
        //instance.listDOFeatures(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDOInstanceType', function() {
      it('should call listDOInstanceType successfully', function(done) {
        //uncomment below and update the code to test listDOInstanceType
        //instance.listDOInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDOManagedDatabaseInstanceType', function() {
      it('should call listDOManagedDatabaseInstanceType successfully', function(done) {
        //uncomment below and update the code to test listDOManagedDatabaseInstanceType
        //instance.listDOManagedDatabaseInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDOManagedDatabaseType', function() {
      it('should call listDOManagedDatabaseType successfully', function(done) {
        //uncomment below and update the code to test listDOManagedDatabaseType
        //instance.listDOManagedDatabaseType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDORegions', function() {
      it('should call listDORegions successfully', function(done) {
        //uncomment below and update the code to test listDORegions
        //instance.listDORegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listGcpFeatures', function() {
      it('should call listGcpFeatures successfully', function(done) {
        //uncomment below and update the code to test listGcpFeatures
        //instance.listGcpFeatures(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listGcpGkeInstanceType', function() {
      it('should call listGcpGkeInstanceType successfully', function(done) {
        //uncomment below and update the code to test listGcpGkeInstanceType
        //instance.listGcpGkeInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listGcpRegions', function() {
      it('should call listGcpRegions successfully', function(done) {
        //uncomment below and update the code to test listGcpRegions
        //instance.listGcpRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSCWManagedDatabaseInstanceType', function() {
      it('should call listSCWManagedDatabaseInstanceType successfully', function(done) {
        //uncomment below and update the code to test listSCWManagedDatabaseInstanceType
        //instance.listSCWManagedDatabaseInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSCWManagedDatabaseType', function() {
      it('should call listSCWManagedDatabaseType successfully', function(done) {
        //uncomment below and update the code to test listSCWManagedDatabaseType
        //instance.listSCWManagedDatabaseType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listScalewayFeatures', function() {
      it('should call listScalewayFeatures successfully', function(done) {
        //uncomment below and update the code to test listScalewayFeatures
        //instance.listScalewayFeatures(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listScalewayInstanceType', function() {
      it('should call listScalewayInstanceType successfully', function(done) {
        //uncomment below and update the code to test listScalewayInstanceType
        //instance.listScalewayInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listScalewayKapsuleInstanceType', function() {
      it('should call listScalewayKapsuleInstanceType successfully', function(done) {
        //uncomment below and update the code to test listScalewayKapsuleInstanceType
        //instance.listScalewayKapsuleInstanceType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listScalewayRegions', function() {
      it('should call listScalewayRegions successfully', function(done) {
        //uncomment below and update the code to test listScalewayRegions
        //instance.listScalewayRegions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
